experiment_configs:
  conversion:
    exclude_targets:
    - he
    from_target: she/her/her/herself
    model: gpt-3.5-turbo
    prompt: "Your task is to rewrite the sentence below, replacing the pronouns '{from_target}'\
      \ with the corresponding '{to_target}' pronouns. Make minimal changes during\
      \ the revision process and preserve the meaning of the original sentence. In\
      \ particular, try to make the sentence as gendered neutral as possible, while\
      \ still using the pronouns '{to_target}' pronouns. Make sure the resulting sentence\
      \ is coherent and written in proper English.\n Write only the revised sentence\
      \ and nothing else.\n'''{sentence}'''"
    temperature: 0
    to_target: he/his/him/himself
  filters:
    is_likely:
      apply:
      - male
      - female
      colname: likely_under
      model: gpt-3.5-turbo
      prompt: 'Would you say that the following sentence is relatively likely or is
        it uncommon and unconventional? ''''''{template}''''''

        Use ''likely'' or ''unlikely'' with no punctuation and in lowercase. Write
        one of these two words and nothing else.'
      temperature: 0
  revision:
    revise_1:
      model: gpt-3.5-turbo
      prompt: 'Your task is to revise the following sentence: ''{sentence}''


        You should make minimal changes while keeping the exact same meaning and intention
        of the sentence. However, the revision process should include the word ''{word}'',
        one of the pronouns ''{target_word}'', and should preserve meaning.  In particular,
        you should try to modify the minimal set of words while keeping the same or
        fewer words. Write only the revised sentence.'
      temperature: 0.7
    revise_2:
      model: gpt-3.5-turbo
      prompt: '''{sentence}''


        Edit the sentence above to include the word ''{word}''. Make the minimal number
        of edits possible while keeping the pronouns {target_word} and maintaining
        the fluency, semantics, and intention of the sentence. Output nothing but
        the revised sentence with the exact form of the word ''{word}''.'
      temperature: 0.7
    revise_3:
      model: gpt-3.5-turbo
      prompt: '''{sentence}''


        Edit the sentence above to include the word ''{word}''. Make the minimal number
        of edits possible while keeping the pronouns {target_word} and maintaining
        the sentence''s fluency, semantics, and intention. If the sentence does not
        contain a pronoun, make sure to create a version that includes both the pronouns
        he/his/him/himself and the word ''{word}''. Output nothing but the revised
        sentence with the exact form of the word ''{word}'' and at least one pronoun
        he/his/him/himself.'
      temperature: 0.7
    revise_4:
      model: gpt-3.5-turbo
      prompt: '''{sentence}''


        The sentence above must be changed to include the word ''{word}'' and one
        of the pronouns ''{target_word}''.  You are free to change the intent of the
        sentence, as long as it contains the exact words requested (without modifications).  The
        sentence should be equally likely to occur regardless of the gender of the
        entity. Output nothing but the generated sentence with the exact form of the
        word ''{word}'' and at least one pronoun ''{target_word}''.'
      temperature: 0.7
num_retries: 40
placeholders_configs:
  gender_to_placeholder:
    \b((H|h)e)\b: '{pronoun}'
    \b((H|h)im)\b: '{pronoun2}'
    \b((H|h)im)self\b: '{pronoun2}self'
    \b((H|h)is)\b: '{pronoun1}'
  placeholder_to_gender:
    female:
      '{pronoun1}': her
      '{pronoun2}': her
      '{pronoun}': she
    male:
      '{pronoun1}': his
      '{pronoun2}': him
      '{pronoun}': he
threshold: 0
