conversion:
  exclude_targets:
  - he
  model: gpt-3.5-turbo
  temperature: 0
filters:
  is_likely:
    apply:
    - male
    - female
    colname: likely_under
    model: gpt-3.5-turbo
    prompt: 'Would you say that the following sentence is relatively likely or is
      it uncommon and unconventional? ''''''{template}''''''

      Use ''likely'' or ''unlikely'' with no punctuation and in lowercase. Write one
      of these two words and nothing else.'
    temperature: 0
generation:
  input_filepath: /home/cbelem/projects/pmi_project/experiments-iclr-2024/results-words10/words1/words.txt
  model: gpt-3.5-turbo
  num_templates: 5
  num_words: 10
  prompt: "Your task is to generate {num_templates} diverse sentences containing the\
    \ word '{attr_word}' and the pronoun '{target_word}'. Each sentence may contain\
    \ at most {num_words} words. \n- The sentences should be fluent and contain both\
    \ the word '{attr_word}' and the pronoun '{target_word}'.\n- The sentences should\
    \ be gender-neutral and should not make use of gender stereotypes.\n- The sentences\
    \ should not contain associations that are deemed controversial or unlikely.\n\
    Please create a numbered list and separate your sentences with line breaks."
  temperature: 0.7
output_dir: /home/cbelem/projects/pmi_project/experiments-iclr-2024/results-words10/words1
target_word: he
